import type { Metadata } from "next";
import { DM_Sans, Inter, Roboto } from "next/font/google";
import "@/styles/global.scss";
import { Header } from "@/components/Header";
import { QueryClient } from "react-query";
import { Providers } from "@/components/Providers";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
  weight: ["400", "500", "700"],
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Linklab Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dm_sans.variable} ${roboto.variable}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
